=== jugurta-benmamas/Site-mygoal/XML/bestplayer.dtd
<!ENTITY % monthval "(1|2|3|4|5|6|7|8|9|10|11|12)">
<!ENTITY % dayval
	 "(1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17|18|19|20|21|22|23|24|25|26|27|28|29|30|31)">
<!ENTITY % year "CDATA"> 
<!ENTITY % amp  "&#38;">
<!ENTITY % bestfoot "(right|left)">
<!ENTITY % nbtimes "(0|1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17|18|19|20|21|22|23|24|25|26|27|28|29|30|31|32|33|34|35|36|37|38|39|40)">

<!ENTITY % heading "h1|h2|h3|h4|h5|h6">
<!ENTITY % lists "ul | ol | dl">
<!ENTITY % blocktext "pre | hr | blockquote | address">
<!ENTITY % block "p | %heading; | div | %lists; | %blocktext; | fieldset | table">
<!ENTITY % Block "(%block; | form | #PCDATA;)*">
<!ENTITY % inline "img | a | highlight">
<!ENTITY % datainline "(#PCDATA | %inline; )*">
<!ENTITY % datainlineul "(#PCDATA | p | %inline; | ul)*">
<!ENTITY % Flow "(#PCDATA | %block; | form | %inline; | %misc;)*">

<!ENTITY % coreattrs
	 "id       ID      #IMPLIED
	  class    CDATA   #IMPLIED
	  title    CDATA   #IMPLIED"
>

<!ENTITY % URI "CDATA">
 <!-- a Uniform Resource Identifier, see [RFC2396] -->

<!ENTITY % Length "CDATA">
<!-- nn for pixels or nn% for percentage length -->


<!ENTITY % Text "CDATA">
    <!-- used for titles etc. -->

    
<!ELEMENT bestfootballplayer (personaldata,biography,palmares,illustrations?) >
<!ATTLIST bestfootballplayer
	  %coreattrs;
	  club    %Text;   #IMPLIED
	  gender    (female|male)  #REQUIRED
	  stillplaying     (yes|no)   #REQUIRED>

<!ELEMENT personaldata (name+,firstname+,pseudo,birth,nationality,sportsnationality,position,bestfoot?)>
<!ATTLIST personaldata
	  %coreattrs;>

<!ELEMENT name (#PCDATA)>
<!ATTLIST name
	  %coreattrs;>

<!ELEMENT firstname (#PCDATA)>
<!ATTLIST firstname
	  %coreattrs;>

<!ELEMENT pseudo (#PCDATA)>
<!ATTLIST pseudo
	  %coreattrs;>

<!ELEMENT birth EMPTY>
<!ATTLIST birth
	  %coreattrs;
	  year     %year;       #REQUIRED
	  month    %monthval;   #IMPLIED
	  day      %dayval;     #IMPLIED
	  >

<!ELEMENT nationality (nationality1,nationality2?)>
<!ATTLIST nationality 
	  %coreattrs;>

<!ELEMENT nationality1 (#PCDATA)>
<!ATTLIST nationality1
%coreattrs;>

<!ELEMENT nationality2 (#PCDATA)>
<!ATTLIST nationality2
%coreattrs;>


<!ELEMENT sportsnationality (#PCDATA)>
<!ATTLIST sportsnationality
	  %coreattrs;>

<!ELEMENT position (#PCDATA)>
<!ATTLIST position
	  %coreattrs;
	  >

<!ELEMENT bestfoot EMPTY>
<!ATTLIST bestfoot
	  %coreattrs;
	  foot %bestfoot; #REQUIRED>


<!ELEMENT biography (youth,firstclub*)>
<!ATTLIST biography
	  %coreattrs;
	  >

<!ELEMENT youth (#PCDATA)>
<!ATTLIST youth
	  %coreattrs;
	  >

<!ELEMENT firstclub (#PCDATA)>
<!ATTLIST firstclub
	  %coreattrs;
	  year %year; #REQUIRED
	  club %Text; #REQUIRED>


<!ELEMENT palmares (asaplayer,asacoach?)>
<!ATTLIST palmares
	  %coreattrs;
	  >
	  

<!ELEMENT asaplayer (squadplayer)*>
<!ATTLIST asaplayer
	  %coreattrs;
	  >

<!ELEMENT asacoach (squadcoach)>
<!ATTLIST asacoach
	  %coreattrs;
	  >

<!ELEMENT squadplayer (#PCDATA,squadname,year,match,goal,decisivepass,victory,trophy)*>
<!ATTLIST squadplayer
		%coreattrs;
		>

<!ELEMENT squadcoach (#PCDATA,squadname,championship,victory)*>
<!ATTLIST squadcoach
	  %coreattrs;
	  >

<!ELEMENT squadname (#PCDATA)>
<!ATTLIST squadname
		%coreattrs;
		id ID #REQUIRED
		>


<!ELEMENT year EMPTY>
<!ATTLIST year
	  %coreattrs;
		year %year; #REQUIRED
		id ID #IMPLIED
	  >

<!ELEMENT championship (#PCDATA)>
<!ATTLIST championship	
	  %coreattrs;
		nbtimes %nbtimes; #IMPLIED
	  >
	  
<!ELEMENT victory EMPTY>
<!ATTLIST victory	
	  %coreattrs;
		year %year; #IMPLIED
		classement %Text; #IMPLIED
		>


<!ELEMENT match (#PCDATA)>
<!ATTLIST match
	  %coreattrs;
	  >

<!ELEMENT goal (#PCDATA)>
<!ATTLIST goal
	  %coreattrs;
	  >

<!ELEMENT decisivepass (#PCDATA)>
<!ATTLIST decisivepass
	  %coreattrs;
	  >

<!ELEMENT trophy (#PCDATA)*>
<!ATTLIST trophy
	  %coreattrs;
	  >


<!ELEMENT ul (li)+>

<!ELEMENT li %datainlineul;>
<!ATTLIST li
		%coreattrs;
		begin %year; #IMPLIED
		end   %year; #IMPLIED
		year  %year; #IMPLIED
		>

<!ELEMENT illustrations (img)+>
<!ATTLIST illustrations
		%coreattrs;
		>

<!ELEMENT img EMPTY>
<!ATTLIST img
		%coreattrs;
		src         %URI; #REQUIRED
		alt         %Text; #REQUIRED
		longdesc    %URI;          #IMPLIED
		height      %Length;       #IMPLIED
		width       %Length;       #IMPLIED
		>



<!ELEMENT a (#PCDATA)*>
<!ATTLIST a
		%coreattrs;
		href        %URI;          #IMPLIED
		>


<!ELEMENT highlight %datainline;>
<!ATTLIST highlight
		%coreattrs;
		>


<!ELEMENT p %datainline;>
<!ATTLIST p
		%coreattrs;
		>

=== jugurta-benmamas/Site-mygoal/XML/joueur1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE bestfootballplayer SYSTEM "bestplayer.dtd">
<bestfootballplayer gender="male" stillplaying="no">
    <personaldata>
        <name>Zidane</name>
        <firstname>Zinédine</firstname>
        <pseudo>Zizou</pseudo>
        <birth year="1972" month="6" day="23" />
        <nationality>
            <nationality1>Français</nationality1>
            <nationality2>Algérien</nationality2>
        </nationality>
        <sportsnationality>Français</sportsnationality>
        <position>Millieu offensif</position>
        <bestfoot foot="right" />
    </personaldata>
    <biography>
        <youth>Depuis la fin des années 1960,la famille Zidane habite dans la cité de La Castellane quartier défavorisé de la ville phocéenne
            où vivent environ 6 000 habitants issus de l'immigration : Maghrébins, noirs africains, espagnols et des comoriens.
            Cette famille de cinq enfants habite dans un appartement de la place Tartane, près du supermarché Casino où travaille Smaïl Zidane, le père de Zinédine.
            C'est sur cette place que « Yazid » ou « Yaz », comme l'appelle son entourage, fait ses premiers pas avec le ballon rond.Avec ses frères et ses amis du quartier,
            le jeune Zidane passe des heures sur l'esplanade en face de son immeuble à jouer au football...</youth>
        <firstclub year="1987" club="AS Cannes">Zinédine Zidane intègre en 1987, à l'âge de quinze ans,
            le centre de formation cannois sous les ordres de Guy Lacombe.À l'AS Cannes, Zidane rencontre de nouveaux entraîneurs et les professionnels de l'équipe première...</firstclub>
    </biography>
    <palmares>
        <asaplayer>
            <squadplayer>
                <squadname id="As Cannes">AS Cannes</squadname>
                <year year="1998-1992"/>
                <match>71 matchs</match>
                <goal>6 buts</goal>
                <trophy>Aucun trophée remporté</trophy>
            </squadplayer>
            <squadplayer>
                <squadname id="Girondins de Bordeaux">Girondins de Bordeaux</squadname>
                <year year="1992"/>
                <match>176 matchs</match>
                <goal>39 buts</goal>
                <victory year="1995">Son premier titre avec la formation bordelaise est la coupe Intertoto</victory>
            </squadplayer>
            <squadplayer>
            <squadname id="Juventus FC">Juventus FC</squadname>
            <year year="1996"/>
            <match>214 matchs</match>
            <goal>31 buts</goal>
            <victory year="1997-1998">Remporte deux titres de champion d'Italie, appelé Scudetto</victory>
        </squadplayer>
        </asaplayer>
        <asacoach>
            <squadcoach>
                <squadname id="Real Madrid">Real Madrid</squadname>
                <championship nbtimes="2">Championnat d'Espagne</championship>
                <victory year="2017" classement="Champion"/>
                <victory year="2020" classement="Champion"/>
                <championship nbtimes="2">Supercoupe d'Espagne</championship>
                <victory year="2017" classement="Vainqueur"/>
                <victory year="2020" classement="Vainqueur"/>
                <championship nbtimes="3">Ligue des champions</championship>
                <victory year="2016" classement="Vainqueur"/>
                <victory year="2017" classement="Vainqueur"/>
                <victory year="2018" classement="Vainqueur"/>
                <championship nbtimes="2">Supercoupe de l'UEFA</championship>
                <victory year="2016" classement="Vainqueur"/>
                <victory year="2017" classement="Vainqueur"/>
                <championship nbtimes="2">Coupe du monde des clubs de la FIFA</championship>
                <victory year="2016" classement="Vainqueur"/>
                <victory year="2017" classement="Vainqueur"/>
            </squadcoach>
        </asacoach>
    </palmares>
    <illustrations>
        <img src="https://assets-fr.imgfoot.com/zinedine-zidane-60586c1fc711d.jpg" alt="zidane" />
    </illustrations>

</bestfootballplayer>

=== jugurta-benmamas/Site-mygoal/XML/joueur2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE bestfootballplayer SYSTEM "bestplayer.dtd">
<bestfootballplayer gender="male" stillplaying="yes" club="psg">
    <personaldata>
        <name>Messi Cuccitini</name>
        <firstname>Lionel Andr√©s</firstname>
        <pseudo>Leo Messi</pseudo>
        <birth year="1987" month="6" day="24" />
        <nationality>
            <nationality1>Argentin</nationality1>
            <nationality2>Espagnol</nationality2>
        </nationality>
        <sportsnationality>Argentin</sportsnationality>
        <position>Attaquant</position>
        <bestfoot foot="left" />
    </personaldata>
    <biography>
        <youth>

        </youth>
        <firstclub year="2000" club="FC Barcelone"></firstclub>
    </biography>
    <palmares>
        <asaplayer>
            <squadplayer>
                <squadname id="FC Barcelone">FC Barcelone</squadname>
                <year year="2003-2004"/>
                <match></match>
                <goal></goal>
                <trophy></trophy>
            </squadplayer>
            <squadplayer>
                <squadname id="Girondins de Bordeaux"></squadname>
                <year year=""/>
                <match></match>
                <goal></goal>
                <victory year=""></victory>
            </squadplayer>
            <squadplayer>
            <squadname id=""></squadname>
            <year year=""/>
            <match></match>
            <goal></goal>
            <victory year=""></victory>
        </squadplayer>
        </asaplayer>
        <asacoach>
            <squadcoach>
                <squadname id=""></squadname>
                <championship nbtimes="0"></championship>
                <victory year="" classement=""/>
                <victory year="" classement=""/>
                <championship nbtimes="0"></championship>
                <victory year="" classement=""/>
                <victory year="" classement=""/>
                <championship nbtimes="0"></championship>
                <victory year="" classement=""/>
                <victory year="" classement=""/>
                <victory year="" classement=""/>
                <championship nbtimes="0"></championship>
                <victory year="" classement=""/>
                <victory year="" classement=""/>
                <championship nbtimes="0"></championship>
                <victory year="" classement=""/>
                <victory year="" classement=""/>
            </squadcoach>
        </asacoach>
    </palmares>
    <illustrations>
        <img src="" alt="" />
    </illustrations>

</bestfootballplayer>
